// Copy this file to env.js and fill in your API keys
// DO NOT commit env.js to git
window.ENV = {
  GOOGLE_MAPS_API_KEY: 'YOUR_GOOGLE_MAPS_API_KEY_HERE',
  FIREBASE_API_KEY: 'YOUR_FIREBASE_API_KEY_HERE',
  FIREBASE_AUTH_DOMAIN: 'YOUR_PROJECT.firebaseapp.com',
  FIREBASE_PROJECT_ID: 'YOUR_PROJECT_ID',
  FIREBASE_STORAGE_BUCKET: 'YOUR_PROJECT.firebasestorage.app',
  FIREBASE_MESSAGING_SENDER_ID: 'YOUR_SENDER_ID',
  FIREBASE_APP_ID: 'YOUR_APP_ID',
  FIREBASE_MEASUREMENT_ID: 'YOUR_MEASUREMENT_ID',
  API_BASE_URL: 'http://localhost:8000'
};
